"""Deterministic renderers and artifact writing.

Everything here is pure Python over validated Pydantic objects. No LLM output
is used as-is: the agents produce structured data, and these functions decide
exactly how it becomes Markdown, CSV, JSON, TypeScript and a ZIP.
"""

from __future__ import annotations

import csv
import io
import json
import zipfile
from datetime import datetime
from pathlib import Path

from ..models import (
    AutomationCandidate,
    CoverageReport,
    JiraIssue,
    PlaywrightBundle,
    RequirementAnalysis,
    RunSummary,
    TestCaseSuite,
    TestPlan,
    TicketResult,
    TicketStatus,
)
from .tickets import safe_path_segment

_GENERATED_NOTE = (
    "> Generated by Jira QA Crew. Every item traces to Jira content; anything "
    "marked INFERRED or ASSUMPTION_REQUIRING_CONFIRMATION needs human review "
    "before it is treated as fact."
)


# --------------------------------------------------------------------------
# Markdown renderers
# --------------------------------------------------------------------------
def render_requirements_md(analysis: RequirementAnalysis, issue: JiraIssue | None = None) -> str:
    lines = [
        f"# Requirements Analysis — {analysis.ticket_key}",
        "",
        _GENERATED_NOTE,
        "",
        f"**Summary:** {analysis.summary}",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Issue type | {analysis.issue_type or 'not set'} |",
        f"| Status | {analysis.status or 'not set'} |",
        f"| Priority | {analysis.priority or 'not set'} |",
        f"| Labels | {', '.join(analysis.labels) or 'none'} |",
        f"| Components | {', '.join(analysis.components) or 'none'} |",
        f"| Parent | {analysis.parent or 'none'} |",
        f"| Subtasks | {', '.join(analysis.subtasks) or 'none'} |",
        f"| Linked issues | {', '.join(analysis.linked_issues) or 'none'} |",
        f"| Fetched via | {analysis.source.value} |",
    ]
    if issue and issue.url:
        lines.append(f"| Jira link | {issue.url} |")
    lines += ["", "## Description Summary", "", analysis.description_summary or "_none_", ""]

    lines += ["## Requirements", ""]
    if analysis.requirements:
        lines += ["| ID | Requirement | Category | Provenance | Source quote |", "| --- | --- | --- | --- | --- |"]
        for req in analysis.requirements:
            lines.append(
                f"| {req.id} | {_cell(req.text)} | {req.category} | "
                f"{req.provenance.value} | {_cell(req.source_quote) or '—'} |"
            )
    else:
        lines.append("_No requirements were extracted._")
    lines.append("")

    lines += ["## Acceptance Criteria", ""]
    if analysis.acceptance_criteria:
        lines += ["| ID | Criterion | Verifies | Provenance |", "| --- | --- | --- | --- |"]
        for criterion in analysis.acceptance_criteria:
            lines.append(
                f"| {criterion.id} | {_cell(criterion.text)} | "
                f"{', '.join(criterion.requirement_ids) or '—'} | {criterion.provenance.value} |"
            )
    else:
        lines.append(
            "_The ticket states no acceptance criteria. None were invented; "
            "see Missing Information._"
        )
    lines.append("")

    for title, values in (
        ("Business Rules", analysis.business_rules),
        ("Non-Functional Requirements", analysis.non_functional_requirements),
        ("Dependencies", analysis.dependencies),
        ("Constraints", analysis.constraints),
        ("Risks", analysis.risks),
        ("Assumptions (require confirmation)", analysis.assumptions),
        ("Missing Information", analysis.missing_information),
        ("Open Questions", analysis.open_questions),
    ):
        lines += [f"## {title}", ""]
        lines += [f"- {v}" for v in values] or ["_none recorded_"]
        lines.append("")
    return "\n".join(lines)


def render_test_plan_md(plan: TestPlan) -> str:
    lines = [f"# {plan.title}", "", _GENERATED_NOTE, "", f"**Ticket:** {plan.ticket_key}", ""]
    for section in plan.sections:
        lines += [f"## {section.number}. {section.title}", "", section.content.strip(), ""]
    if plan.scenarios:
        lines += ["## Scenario Index", "", "| ID | Scenario | Priority | Traces to |", "| --- | --- | --- | --- |"]
        for scenario in plan.scenarios:
            refs = ", ".join([*scenario.requirement_ids, *scenario.acceptance_criteria_ids])
            lines.append(
                f"| {scenario.id} | {_cell(scenario.title)} | {scenario.priority.value} | {refs} |"
            )
        lines.append("")
    return "\n".join(lines)


def render_test_cases_md(suite: TestCaseSuite) -> str:
    lines = [
        f"# Test Cases — {suite.ticket_key}",
        "",
        _GENERATED_NOTE,
        "",
        f"**Total test cases:** {len(suite.test_cases)}",
        "",
    ]
    if suite.coverage_notes:
        lines += ["## Coverage Notes", "", suite.coverage_notes.strip(), ""]

    for case in suite.test_cases:
        lines += [
            f"## {case.id} — {case.title}",
            "",
            f"- **Ticket:** {case.ticket_key}",
            f"- **Priority:** {case.priority.value}",
            f"- **Type:** {case.test_type.value}",
            f"- **Requirements:** {', '.join(case.requirement_ids) or '—'}",
            f"- **Acceptance criteria:** {', '.join(case.acceptance_criteria_ids) or '—'}",
            f"- **Automation candidate:** {case.automation_candidate.value}"
            + (f" — {case.automation_rationale}" if case.automation_rationale else ""),
            f"- **Tags:** {', '.join(case.tags) or '—'}",
            "",
            f"**Objective:** {case.objective or '—'}",
            "",
        ]
        if case.preconditions:
            lines += ["**Preconditions:**", *[f"- {p}" for p in case.preconditions], ""]
        if case.test_data:
            lines += ["**Test data:**", *[f"- {d}" for d in case.test_data], ""]
        lines += ["| # | Action | Expected |", "| --- | --- | --- |"]
        for step in case.steps:
            lines.append(f"| {step.number} | {_cell(step.action)} | {_cell(step.expected) or '—'} |")
        lines += ["", f"**Expected result:** {case.expected_result or '—'}", ""]
        if case.assumptions_or_blockers:
            lines += [
                "**Assumptions / blockers:**",
                *[f"- {b}" for b in case.assumptions_or_blockers],
                "",
            ]
    return "\n".join(lines)


def render_playwright_md(bundle: PlaywrightBundle) -> str:
    lang = {"ts": "typescript", "js": "javascript"}
    lines = [
        f"# Playwright Automation — {bundle.ticket_key}",
        "",
        _GENERATED_NOTE,
        "",
        f"**Automation readiness:** `{bundle.readiness.value}`",
        "",
    ]
    if bundle.readiness.value == "NEEDS_CONFIGURATION":
        lines += [
            "> This code compiles but is **not execution-ready**. The items under "
            "Missing Information must be supplied first.",
            "",
        ]
    if bundle.setup_notes:
        lines += ["## Setup", "", bundle.setup_notes.strip(), ""]

    if bundle.traces:
        lines += [
            "## Coverage",
            "",
            "| Test | Test case | Requirements | Acceptance criteria | File |",
            "| --- | --- | --- | --- | --- |",
        ]
        for trace in bundle.traces:
            lines.append(
                f"| {_cell(trace.test_name)} | {trace.test_case_id} | "
                f"{', '.join(trace.requirement_ids) or '—'} | "
                f"{', '.join(trace.acceptance_criteria_ids) or '—'} | {trace.spec_path or '—'} |"
            )
        lines.append("")

    lines += ["## Generated files", ""]
    for file in bundle.files:
        fence = lang.get(file.path.rsplit(".", 1)[-1], "typescript")
        lines += [f"### `{file.path}`", "", f"```{fence}", file.content.rstrip(), "```", ""]

    for title, values in (
        ("Missing Information", bundle.missing_information),
        ("Assumptions", bundle.assumptions),
    ):
        lines += [f"## {title}", ""]
        lines += [f"- {v}" for v in values] or ["_none_"]
        lines.append("")
    return "\n".join(lines)


def render_run_summary_md(run: RunSummary) -> str:
    lines = [
        "# Run Summary",
        "",
        f"**Run ID:** {run.run_id}",
        f"**Started:** {_stamp(run.started_at)}",
        f"**Finished:** {_stamp(run.finished_at)}",
        "",
        f"- Tickets requested: {len(run.requested_keys)}",
        f"- Completed: {len(run.completed)}",
        f"- Completed with warnings: {len(run.completed_with_warnings)}",
        f"- Failed: {len(run.failed)}",
        "",
    ]
    if run.invalid_inputs:
        lines += [f"- Rejected input tokens: {', '.join(run.invalid_inputs)}", ""]
    if run.duplicates_removed:
        lines += [f"- Duplicates removed: {', '.join(run.duplicates_removed)}", ""]

    lines += [
        "| Ticket | Status | Source | Automation | Requirements | Test cases | Coverage |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for result in run.results:
        coverage = (
            f"{result.coverage.requirement_coverage_pct}%" if result.coverage else "—"
        )
        lines.append(
            f"| {result.ticket_key} | {result.status.value} | "
            f"{result.source.value if result.source else '—'} | "
            f"{result.playwright.readiness.value if result.playwright else '—'} | "
            f"{result.coverage.total_requirements if result.coverage else 0} | "
            f"{result.coverage.total_test_cases if result.coverage else 0} | {coverage} |"
        )
    lines.append("")

    failures = run.failed
    if failures:
        lines += ["## Failures", ""]
        for result in failures:
            lines.append(f"- **{result.ticket_key}**: {result.error}")
        lines.append("")

    warned = [r for r in run.results if r.warnings]
    if warned:
        lines += ["## Warnings", ""]
        for result in warned:
            lines.append(f"- **{result.ticket_key}**")
            lines += [f"  - {w}" for w in result.warnings]
        lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# CSV renderers
# --------------------------------------------------------------------------
def render_test_cases_csv(suite: TestCaseSuite) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(
        [
            "test_case_id", "ticket_key", "title", "objective", "priority", "test_type",
            "requirement_ids", "acceptance_criteria_ids", "preconditions", "test_data",
            "steps", "expected_result", "automation_candidate", "automation_rationale",
            "tags", "assumptions_or_blockers",
        ]
    )
    for case in suite.test_cases:
        writer.writerow(
            [
                case.id, case.ticket_key, case.title, case.objective,
                case.priority.value, case.test_type.value,
                "; ".join(case.requirement_ids), "; ".join(case.acceptance_criteria_ids),
                " | ".join(case.preconditions), " | ".join(case.test_data),
                " | ".join(
                    f"{s.number}. {s.action}" + (f" -> {s.expected}" if s.expected else "")
                    for s in case.steps
                ),
                case.expected_result, case.automation_candidate.value,
                case.automation_rationale, "; ".join(case.tags),
                " | ".join(case.assumptions_or_blockers),
            ]
        )
    return buffer.getvalue()


def render_traceability_csv(coverage: CoverageReport) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(
        [
            "requirement_id", "requirement_text", "acceptance_criterion_id",
            "acceptance_criterion_text", "test_case_ids", "automated_test_case_ids",
            "coverage_status", "reason",
        ]
    )
    for row in coverage.rows:
        writer.writerow(
            [
                row.requirement_id, row.requirement_text, row.acceptance_criterion_id,
                row.acceptance_criterion_text, "; ".join(row.test_case_ids),
                "; ".join(row.automated_test_case_ids), row.coverage_status.value, row.reason,
            ]
        )
    return buffer.getvalue()


# --------------------------------------------------------------------------
# Manifests
# --------------------------------------------------------------------------
def build_ticket_manifest(result: TicketResult) -> dict:
    coverage = result.coverage
    return {
        "ticket_key": result.ticket_key,
        "status": result.status.value,
        "source": result.source.value if result.source else None,
        "jira_url": result.issue.url if result.issue else "",
        "fetched_at": _stamp(result.issue.fetched_at) if result.issue else None,
        "started_at": _stamp(result.started_at),
        "finished_at": _stamp(result.finished_at),
        "duration_seconds": result.duration_seconds,
        "counts": {
            "requirements": len(result.analysis.requirements) if result.analysis else 0,
            "acceptance_criteria": (
                len(result.analysis.acceptance_criteria) if result.analysis else 0
            ),
            "test_cases": len(result.test_cases.test_cases) if result.test_cases else 0,
            "automation_candidates": (
                len(
                    [
                        c
                        for c in result.test_cases.test_cases
                        if c.automation_candidate is not AutomationCandidate.NO
                    ]
                )
                if result.test_cases
                else 0
            ),
            "playwright_files": len(result.playwright.files) if result.playwright else 0,
        },
        "coverage": (
            {
                "requirement_coverage_pct": coverage.requirement_coverage_pct,
                "automation_pct": coverage.automation_pct,
                "covered_requirements": coverage.covered_requirements,
                "partially_covered_requirements": coverage.partially_covered_requirements,
                "uncovered_requirements": coverage.uncovered_requirements,
                "orphan_requirement_ids": coverage.orphan_requirement_ids,
                "orphan_test_case_ids": coverage.orphan_test_case_ids,
                "unknown_reference_ids": coverage.unknown_reference_ids,
            }
            if coverage
            else None
        ),
        "automation_readiness": (
            result.playwright.readiness.value if result.playwright else None
        ),
        "missing_information": (
            result.playwright.missing_information if result.playwright else []
        ),
        "warnings": result.warnings,
        "error": result.error,
        "artifacts": result.artifacts,
        "stages": [
            {
                "stage": s.stage.value,
                "status": s.status.value,
                "message": s.message,
                "duration_seconds": s.duration_seconds,
            }
            for s in result.stages
        ],
    }


def build_run_manifest(run: RunSummary) -> dict:
    return {
        "run_id": run.run_id,
        "generator": "Jira QA Crew",
        "started_at": _stamp(run.started_at),
        "finished_at": _stamp(run.finished_at),
        "requested_keys": run.requested_keys,
        "invalid_inputs": run.invalid_inputs,
        "duplicates_removed": run.duplicates_removed,
        "totals": {
            "requested": len(run.requested_keys),
            "completed": len(run.completed),
            "completed_with_warnings": len(run.completed_with_warnings),
            "failed": len(run.failed),
        },
        "successful": run.successful,
        "tickets": [build_ticket_manifest(r) for r in run.results],
    }


# --------------------------------------------------------------------------
# Writing to disk
# --------------------------------------------------------------------------
def write_ticket_artifacts(result: TicketResult, run_dir: Path) -> dict[str, str]:
    """Write every artifact for one ticket. Returns ``{name: relative path}``."""
    ticket_dir = run_dir / safe_path_segment(result.ticket_key)
    ticket_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}

    def _write(name: str, content: str, subdir: Path | None = None) -> None:
        target = (subdir or ticket_dir) / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written[name] = str(target.relative_to(run_dir))

    if result.analysis:
        _write("requirements_analysis.md", render_requirements_md(result.analysis, result.issue))
        _write(
            "requirements_analysis.json",
            json.dumps(result.analysis.model_dump(mode="json"), indent=2),
        )
    if result.test_plan:
        _write("test_plan.md", render_test_plan_md(result.test_plan))
    if result.test_cases:
        _write("test_cases.md", render_test_cases_md(result.test_cases))
        _write("test_cases.csv", render_test_cases_csv(result.test_cases))
    if result.coverage:
        _write("traceability_matrix.csv", render_traceability_csv(result.coverage))
    if result.playwright:
        _write("playwright_tests.md", render_playwright_md(result.playwright))
        pw_root = ticket_dir / "playwright"
        for sub in ("tests", "pages", "fixtures"):
            (pw_root / sub).mkdir(parents=True, exist_ok=True)
        for file in result.playwright.files:
            safe_parts = [safe_path_segment(p) for p in Path(file.path).parts]
            target = pw_root.joinpath(*safe_parts)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(file.content, encoding="utf-8")
            written[file.path] = str(target.relative_to(run_dir))

    manifest = build_ticket_manifest(result)
    manifest["artifacts"] = dict(written)
    (ticket_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    written["manifest.json"] = str((ticket_dir / "manifest.json").relative_to(run_dir))

    result.artifact_dir = str(ticket_dir)
    result.artifacts = written
    return written


def write_run_artifacts(run: RunSummary, output_dir: Path) -> Path:
    """Write the run-level summary and manifest, and return the run directory."""
    run_dir = output_dir / safe_path_segment(run.run_id)
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "run_summary.md").write_text(render_run_summary_md(run), encoding="utf-8")
    (run_dir / "manifest.json").write_text(
        json.dumps(build_run_manifest(run), indent=2), encoding="utf-8"
    )
    run.output_dir = str(run_dir)
    return run_dir


# --------------------------------------------------------------------------
# ZIP
# --------------------------------------------------------------------------
def build_zip(run: RunSummary, tickets: list[str] | None = None) -> bytes:
    """Bundle artifacts into a ZIP, built on demand rather than kept in memory.

    ``tickets`` limits the bundle to specific ticket keys; the default is the
    whole run.
    """
    wanted = {t.strip().upper() for t in tickets} if tickets else None
    buffer = io.BytesIO()

    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(f"{run.run_id}/run_summary.md", render_run_summary_md(run))
        archive.writestr(
            f"{run.run_id}/manifest.json", json.dumps(build_run_manifest(run), indent=2)
        )
        for result in run.results:
            if wanted and result.ticket_key.upper() not in wanted:
                continue
            if result.status is TicketStatus.FAILED and not result.analysis:
                continue
            base = f"{run.run_id}/{safe_path_segment(result.ticket_key)}"
            for name, content in _ticket_files(result):
                archive.writestr(f"{base}/{name}", content)

    buffer.seek(0)
    return buffer.getvalue()


def _ticket_files(result: TicketResult) -> list[tuple[str, str]]:
    """The in-memory file list for one ticket, rendered deterministically."""
    files: list[tuple[str, str]] = []
    if result.analysis:
        files.append(
            ("requirements_analysis.md", render_requirements_md(result.analysis, result.issue))
        )
        files.append(
            (
                "requirements_analysis.json",
                json.dumps(result.analysis.model_dump(mode="json"), indent=2),
            )
        )
    if result.test_plan:
        files.append(("test_plan.md", render_test_plan_md(result.test_plan)))
    if result.test_cases:
        files.append(("test_cases.md", render_test_cases_md(result.test_cases)))
        files.append(("test_cases.csv", render_test_cases_csv(result.test_cases)))
    if result.coverage:
        files.append(("traceability_matrix.csv", render_traceability_csv(result.coverage)))
    if result.playwright:
        files.append(("playwright_tests.md", render_playwright_md(result.playwright)))
        for file in result.playwright.files:
            safe = "/".join(safe_path_segment(p) for p in Path(file.path).parts)
            files.append((f"playwright/{safe}", file.content))
    files.append(("manifest.json", json.dumps(build_ticket_manifest(result), indent=2)))
    return files


# --------------------------------------------------------------------------
def _cell(text: str) -> str:
    """Make a string safe for a Markdown table cell."""
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def _stamp(value: datetime | None) -> str | None:
    return value.isoformat(timespec="seconds") if value else None
